title: APS Digitization Docs
email: sbocanegra@amphilsoc.org
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: /APS-Digitization # the subpath of your site, e.g. /blog
url: "https://AmericanPhilosophicalSociety.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed

last_edit_timestamp: true
last_edit_time_format: "%B %e %Y"
